name: Run

on:
  push:
    branches:
      - main
  schedule:
    - cron: '6 10 * * *'  # 在UTC时间上午10点6分运行
  workflow_dispatch:  # 手动触发


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 选择所需的 Python 版本

    - name: Install dependencies
      run: pip install -r requirements.txt  # 根据你的需求修改 requirements.txt 文件路径

    - name: Run
      env:
        SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        ACCOUNT_INFO: ${{ secrets.ACCOUNT_INFO }}
      run: python steps.py
